const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.CreateObject
	];
};
self.C3_JsPropNameTable = [
	{Платформер: 0},
	{СледитьЗа: 0},
	{ОграничитьСценой: 0},
	{персонаж: 0},
	{Твёрдый: 0},
	{песчаник: 0},
	{ТайловыйФон: 0},
	{кактус: 0},
	{Якорь: 0},
	{здоровье: 0},
	{земля: 0},
	{трава: 0},
	{ствол: 0},
	{листва: 0},
	{жемчуг: 0},
	{Аудио: 0},
	{Мышь: 0},
	{ПесчанникЧастицы: 0},
	{ЗемляЧастицы: 0},
	{КактусЧастицы: 0},
	{ДистанцияВзаимодействия: 0}
];

self.InstanceType = {
	персонаж: class extends self.ISpriteInstance {},
	песчаник: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	кактус: class extends self.ISpriteInstance {},
	здоровье: class extends self.ITiledBackgroundInstance {},
	земля: class extends self.ISpriteInstance {},
	трава: class extends self.ISpriteInstance {},
	ствол: class extends self.ISpriteInstance {},
	листва: class extends self.ISpriteInstance {},
	жемчуг: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	ПесчанникЧастицы: class extends self.IParticlesInstance {},
	ЗемляЧастицы: class extends self.IParticlesInstance {},
	КактусЧастицы: class extends self.IParticlesInstance {}
}